Improvement/add validations for output file extensions
carbonetes/diggity pull request #77
Opened 2023-05-09 07:07 UTC by gxcarbo

2023-05-09 11:15 UTC, kirkalynsantos requested changes

2023-05-09 11:15 UTC, kirkalynsantos commented on pkg/files/files_test.go
Same changes from this file also exists in another PR. 
https://github.com/carbonetes/diggity/pull/76/files

2023-05-10 04:32 UTC, gxcarbo commented
My issues po sa PR, Pa Decline po. Thanks

2023-05-10 05:00 UTC, kirkalynsantos commented
Declining as per request.

2023-05-10 05:00 UTC, closed without merging